using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Showcase.AudioOrchestration;

public interface IAgent
{
    /// <summary>
    /// Process data frames.
    /// </summary>
    Task ProcessInboundDataAsync(DataFrame frame, CancellationToken cancellationToken);

    /// <summary>
    /// Process outbound data frames (i.e. generated by the AI conversation).
    /// </summary>
    Task ProcessOutboundDataAsync(DataFrame frame, CancellationToken cancellationToken);

}
