using OpenAI.RealtimeConversation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Showcase.AudioOrchestration;
#pragma warning disable OPENAI002

public interface IConversationAgent : IAsyncDisposable
{
    /// <summary>
    /// Process inbound audio frames coming from the external source.
    /// </summary>
    Task ProcessInboundAudioAsync(AudioFrame frame, CancellationToken cancellationToken);

    /// <summary>
    /// Process outbound audio frames (i.e. generated by the AI conversation).
    /// </summary>
    Task ProcessConversationUpdateAsync(ConversationUpdate update, CancellationToken cancellationToken);

    /// <summary>
    /// Process a command (e.g. override instructions) coming from auditing agents.
    /// </summary>
    Task ProcessInboundFeedbackAsync(AiAgentCommand command, CancellationToken cancellationToken);
}
